# Generated by Django 3.1.2 on 2021-03-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_detail',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone_no', models.IntegerField(default=0, max_length=12)),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
