# Generated by Django 3.1.2 on 2021-03-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proapp', '0002_contact_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_detail',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
